INSERT INTO District(`name`) VALUES 
	('Chorągiew Harcerzy Ziemi Opolskiej'),
	('Górnośląska Chorągiew Harcerzy'),
	('Dolnośląska Chorągiew Harcerzy'),
	('Kujawsko-Pomorska Chorągiew Harcerzy'),
	('Łódzka Chorągiew Harcerzy'),
	('Lubelska Chorągiew Harcerzy'),
	('Małopolska Chorągiew Harcerzy'),
	('Wielkopolska Chorągiew Harcerzy'),
	('Staropolska Chorągiew Harcerzy'),
	('Pomorska Chorągiew Harcerzy'),
	('Północno-Zachodnia Chorągiew Harcerzy'),
	('Północno-Wschodnia Chorągiew Harcerzy'),
	('Podkarpacka Chorągiew Harcerzy'),
	('Mazowiecka Chorągiew Harcerzy');
