services:
  frontend:
    build: frontend
    restart: always
#    env_file:
#      - frontend/.env
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
  backend:
    build: backend
    restart: always
#    env_file:
#      - backend/.env
    environment:
      OAUTH_GOOGLE_ID:
      OAUTH_GOOGLE_SECRET:
      BASEURL: http://localhost:8080
      REDIS_URL: redis://redis:6379
      DATABASE_URL: mysql://master:master@mysql:3306/kategoryzacja
      BCRYPT_ROUNDS: 11
  mysql:
    image: mariadb:11
    restart: always
    command: --max-allowed-packet=65011712
    volumes:
      - './database:/var/lib/mysql'
    environment:
      MARIADB_PASSWORD: master
      MARIADB_USER: master
      MARIADB_DATABASE: kategoryzacja
      MARIADB_RANDOM_ROOT_PASSWORD: yes
  redis:
    image: redis:alpine
    restart: always
    command: >
      --protected-mode no
      --save ""
      --appendonly no
  nginx:
    build: nginx
    restart: always
