services:
  frontend:
    image: michalmajzhr/kategoryzacja-harcerze-zhr-frontend:v1.4
    restart: always
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
  backend-w1:
    image: michalmajzhr/kategoryzacja-harcerze-zhr-backend:v1.4
    restart: always
    environment:
      OAUTH_GOOGLE_ID:
      OAUTH_GOOGLE_SECRET:
      SMTP_LOGIN:
      SMTP_PASSWORD:
      BASEURL: http://localhost:8080
      REDIS_URL: redis://redis:6379
      DATABASE_URL: mysql://master:master@mysql:3306/kategoryzacja
      BCRYPT_ROUNDS: 11
  backend-w2:
    image: michalmajzhr/kategoryzacja-harcerze-zhr-backend:v1.4
    restart: always
    environment:
      OAUTH_GOOGLE_ID:
      OAUTH_GOOGLE_SECRET:
      SMTP_LOGIN:
      SMTP_PASSWORD:
      BASEURL: http://localhost:8080
      REDIS_URL: redis://redis:6379
      DATABASE_URL: mysql://master:master@mysql:3306/kategoryzacja
      BCRYPT_ROUNDS: 11
  backend-w3:
    image: michalmajzhr/kategoryzacja-harcerze-zhr-backend:v1.4
    restart: always
    environment:
      OAUTH_GOOGLE_ID:
      OAUTH_GOOGLE_SECRET:
      SMTP_LOGIN:
      SMTP_PASSWORD:
      BASEURL: http://localhost:8080
      REDIS_URL: redis://redis:6379
      DATABASE_URL: mysql://master:master@mysql:3306/kategoryzacja
      BCRYPT_ROUNDS: 11
  backend-w4:
    image: michalmajzhr/kategoryzacja-harcerze-zhr-backend:v1.4
    restart: always
    environment:
      OAUTH_GOOGLE_ID:
      OAUTH_GOOGLE_SECRET:
      SMTP_LOGIN:
      SMTP_PASSWORD:
      BASEURL: http://localhost:8080
      REDIS_URL: redis://redis:6379
      DATABASE_URL: mysql://master:master@mysql:3306/kategoryzacja
      BCRYPT_ROUNDS: 11
  crontab:
    image: michalmajzhr/kategoryzacja-harcerze-zhr-cron:v1.4
    restart: always
    environment:
      SMTP_LOGIN:
      SMTP_PASSWORD:
      BASEURL: http://localhost:8080
      REDIS_URL: redis://redis:6379
      DATABASE_URL: mysql://master:master@mysql:3306/kategoryzacja
      BCRYPT_ROUNDS: 11
  mysql:
    image: mariadb:11
    restart: always
    command: --max-allowed-packet=65011712
    volumes:
      - './database:/var/lib/mysql'
    environment:
      MARIADB_PASSWORD: master
      MARIADB_USER: master
      MARIADB_DATABASE: kategoryzacja
      MARIADB_RANDOM_ROOT_PASSWORD: yes
  redis:
    image: redis:alpine
    restart: always
    command: >
      --protected-mode no
      --save ""
      --appendonly no
  nginx:
    image: michalmajzhr/kategoryzacja-harcerze-zhr-nginx:v1.4
    restart: always
